version: "3.8"

services:
  orchid-backend-net.api:
    image: ${DOCKER_REGISTRY:-orchidbackendnetapi}
    build:
      context: .
      dockerfile: orchid-backend-net.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - REDIS_HOST=orchid-redis
      - VIRTUAL_HOST=api.orchid-lab.systems
      - LETSENCRYPT_HOST=api.orchid-lab.systems
      - LETSENCRYPT_EMAIL=dotranlam2003@gmail.com
    expose:
      - "8080"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - orchid-redis
    networks:
      - backend-network
    restart: always

  orchid-redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    expose:
      - "6379"  # expose thay vì publish port nếu chỉ dùng nội bộ
    networks:
      - backend-network
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - backend-network
    restart: always

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=dotranlam2003@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  redis-data:
    driver: local