version: "3.8"

services:
  orchid-backend-net.api:
    image: ${DOCKER_REGISTRY:-orchidbackendnetapi}
    build:
      context: .
      dockerfile: orchid-backend-net.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - REDIS_HOST=orchid-redis
    expose:
      - "8080"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - orchid-redis
    networks:
      - backend-network
    restart: always

  orchid-redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  redis-data:
    driver: local